### ISSUE TITLE
How to Set VirtualPathRoot 

### ISSUE THREAD

**Issue by zljie** [jlucansky/Quartzmin#13]
Hello, this is so so great, wonderful job!
       I'm trying to publish Quartzmin in VirtualPath Website By  variable（VirtualPathRoot） .but it doesn't work ,it look like duplicate use VirtualPathRoot. my environment is asp.net mvc
![i3](https://user-images.githubusercontent.com/44569452/54914294-9b5aff00-4f2f-11e9-8522-13fa92f69590.png)
![i4](https://user-images.githubusercontent.com/44569452/54914296-9bf39580-4f2f-11e9-93e2-b873809dce71.png)
![i5](https://user-images.githubusercontent.com/44569452/54965133-28429e80-4faa-11e9-9a98-54684c642e9a.png)

**Comment by eflorespalma** [comment]
Hi @zljie , did you solve this?

**Comment by maikebing** [comment]
Fix for Asp.Net Core 3.1 and fixe for VirtualPathRoot https://github.com/jlucansky/Quartzmin/pull/27

**Comment by xico002** [comment]
Hi! I'm using .net core 2.2. Sorry but i don't understand how do you change the path root.

**Comment by devigo** [comment]
@xico002 
You can try to fix `VirtualPathRoot` from `QuartzminOptions` in .NET Core

``` csharp
app.UseQuartzmin(new QuartzminOptions()
{
    Scheduler = StdSchedulerFactory.GetDefaultScheduler().Result,
    VirtualPathRoot = "/quartz",
});
```

**Comment by zljie** [comment]
thank for your help

app.UseQuartzmin(new QuartzminOptions()
{
    Scheduler = StdSchedulerFactory.GetDefaultScheduler().Result,
    VirtualPathRoot = "/quartz",
});
