### ISSUE TITLE
How to use in AspNet Core MVC Full Framework (4.6.1) ?

### ISSUE THREAD

**Issue by victorperez2911** [jlucansky/Quartzmin#17]
How to configure for use with an AspNet Core MVC project, but with Full Framework as target?

![image](https://user-images.githubusercontent.com/11770654/59517543-34981280-8e9a-11e9-99b7-9081b0a26788.png)

**Comment by jlucansky** [comment]
ASP.NET Core MVC cannot be referenced from full framework. 
See example [AspNetWebHost](https://github.com/jlucansky/Quartzmin/tree/master/Source/Examples/AspNetWebHost ) how you can use Quartzmin from full framework.
