### ISSUE TITLE
Dependency injection on IJob

### ISSUE THREAD

**Issue by ngvtien** [jlucansky/Quartzmin#3]
Can you possibly give an example of how to make use of IoC inside a job? eg passing dependency in the job constructor.

Cheers,
Tien

**Comment by jlucansky** [comment]
Hi, you can configure custom ISchedulerFactory which is not specific to Quartzmin or pass custom object via Scheduler.Context

**Comment by ngvtien** [comment]
Sure, too easy! 
Cheers
