### ISSUE TITLE
How to host Quartzmin on IIS?

### ISSUE THREAD

**Issue by naveedzaidi36** [jlucansky/Quartzmin#35]
Hi Guys,
I have used Quartzmin for my working and created a Windows Service.
Right now Quartzmin SelfHost is running on localhost:5000, which I provided in configuration key "quartz.plugin.quartzmin.url"
Now, I want to deploy this interface on IIS to make it publicly accessible. How can I do this?
Keeping in mind that I have Windows Service. 

@jlucansky  @vmutyal

**Comment by jlucansky** [comment]
Hi, to host in IIS you can use example at https://github.com/jlucansky/Quartzmin/tree/master/Source/Examples/AspNetWebHost
